feat: cloudflare turnstile verify page
bangumi/server-private pull request #767
Opened 2024-10-11 04:27 UTC by MisakaTAT

2024-10-11 11:49 UTC, trim21 commented
@everpcpc

2024-10-11 12:00 UTC, everpcpc commented
这个是干啥用的？

2024-10-11 12:00 UTC, trim21 commented
> 这个是干啥用的？

帮助客户端过验证码的

2024-10-11 12:03 UTC, everpcpc commented on templates/turnstile.liquid
> +    console.log(JSON.stringify(resp));
是准备在这里跳转 app 这样子吗

2024-10-12 07:48 UTC, MisakaTAT commented on templates/turnstile.liquid
> +    console.log(JSON.stringify(resp));
目前是app直接从console或者dom获取token

2024-10-14 04:19 UTC, StageGuard commented
目前直接打印到 console 获取可能不是太好. 我觉得可以这样:

query param 必须指定两个查询字段
* request_id 传递 client 用来标识的解题 id
* callback_url 传递解题完成后的回调 url

解题完成后回调到 callback_url?request_id=上面客户端查询的request_id&cf_turnstile_response=解题结果

2024-10-14 04:58 UTC, everpcpc commented on templates/turnstile.liquid
> +    console.log(JSON.stringify(resp));
我还以为这只debug用的

一般不太会把console输出拿来当正式用途吧

2024-10-14 05:01 UTC, everpcpc commented
> 目前直接打印到 console 获取可能不是太好. 我觉得可以这样:
> 
> 
> 
> query param 必须指定两个查询字段
> 
> * request_id 传递 client 用来标识的解题 id
> 
> * callback_url 传递解题完成后的回调 url
> 
> 
> 
> 解题完成后回调到 callback_url?request_id=上面客户端查询的request_id&cf_turnstile_response=解题结果
> 
> 
> 
> 让 client app 自己设置 url handler 处理回调 
> 
> 
> 
> BGM 服务端不需要存储 request_id，仅仅是客户端的标识，但是可能要防止注入之类的验证
> 
> @MisakaTAT 

request_id 也不需要，类似 oauth 有一个 redirect uri，然后把 token 附到参数里面就好了

2024-10-14 05:31 UTC, MisakaTAT commented
> > 目前直接打印到 console 获取可能不是太好. 我觉得可以这样:
> > query param 必须指定两个查询字段
> > 
> > * request_id 传递 client 用来标识的解题 id
> > * callback_url 传递解题完成后的回调 url
> > 
> > 解题完成后回调到 callback_url?request_id=上面客户端查询的request_id&cf_turnstile_response=解题结果
> > 让 client app 自己设置 url handler 处理回调
> > BGM 服务端不需要存储 request_id，仅仅是客户端的标识，但是可能要防止注入之类的验证
> > @MisakaTAT
> 
> request_id 也不需要，类似 oauth 有一个 redirect uri，然后把 token 附到参数里面就好了

需不需要必须注册app才允许调用turnstile？

目前想的是两个方式

在请求的时候携带 redirect_uri 参数
```
client -> bgmapi.com/turnstile?redirect_uri=http://my_redirect_uri.com -> http://my_redirect_uri.com?cf_turnstile_token={token}
```

在请求的时候携带 client_id 参数，去查 app oauth 表的 redirect_uri。
```
请求携带 client_id，去查 app oauth 的 redirect_uri，验证完成后在这个 redirect_uri 附上 ?cf_turnstile_token={token} 参数
```
@everpcpc

2024-10-14 05:36 UTC, MisakaTAT commented on templates/turnstile.liquid
> +    console.log(JSON.stringify(resp));
> 我还以为这只debug用的
> 
> 一般不太会把console输出拿来当正式用途吧

其实就是没想好（，所以是draft pr

2024-10-14 05:36 UTC, everpcpc commented
感觉不需要再验证一次 client_id，带 redirect_uri 就好。
因为即使非认证客户端拿到一个 cf token 也没什么影响，毕竟自己随便本地写个页面加载下 cf 的 js 也能拿到这个 token 的

2024-10-14 05:43 UTC, StageGuard commented
> 感觉不需要再验证一次 client_id，带 redirect_uri 就好。 因为即使非认证客户端拿到一个 cf token 也没什么影响，毕竟自己随便本地写个页面加载下 cf 的 js 也能拿到这个 token 的

之前评论接口 merge 的时候我测试过在本地页面填 bgm 的 sitekey 加载验证，发现 turnstile 会报错，cf 提供的 dummy key 就可以，所以我觉得 turnstile 应该是没办法随便就能过的，有很多检测手段

2024-10-14 05:48 UTC, everpcpc commented
> 之前评论接口 merge 的时候我测试过在本地页面填 bgm 的 sitekey 加载验证，发现 turnstile 会报错，cf 提供的 dummy key 就可以，所以我觉得 turnstile 应该是没办法随便就能过的，有很多检测手段

https://github.com/bangumi/server-private/blob/master/lib/services/turnstile.ts#L33
但是 server 端去 verify token 的时候没有拿任何 client 的内容啊，只 verify 了 cf 返回的 response

2024-10-14 05:59 UTC, MisakaTAT commented
改了改，再看看？模板里面好像只能这么重定向

2024-10-14 05:59 UTC, StageGuard commented
> > 之前评论接口 merge 的时候我测试过在本地页面填 bgm 的 sitekey 加载验证，发现 turnstile 会报错，cf 提供的 dummy key 就可以，所以我觉得 turnstile 应该是没办法随便就能过的，有很多检测手段
> 
> https://github.com/bangumi/server-private/blob/master/lib/services/turnstile.ts#L33 但是 server 端去 verify token 的时候没有拿任何 client 的内容啊，只 verify 了 cf 返回的 response

我的意思是 turnstile 自身的各种检测，他可能会检测请求 header ，浏览器环境之类的，不是 server 端的检测。
回到刚刚的问题，不带 client_id 也没什么问题，但是现在访问的需要带 turnstile token 的 API 都是 oauth 验证之后才能访问吧？那我觉得把 "请求解 turnstile" 和 "需要注册 oauth app" 这两件事情绑定也没什么副作用。

2024-10-14 06:01 UTC, MisakaTAT commented
> > > 之前评论接口 merge 的时候我测试过在本地页面填 bgm 的 sitekey 加载验证，发现 turnstile 会报错，cf 提供的 dummy key 就可以，所以我觉得 turnstile 应该是没办法随便就能过的，有很多检测手段
> > 
> > 
> > https://github.com/bangumi/server-private/blob/master/lib/services/turnstile.ts#L33 但是 server 端去 verify token 的时候没有拿任何 client 的内容啊，只 verify 了 cf 返回的 response
> 
> 我的意思是 turnstile 自身的各种检测，他可能会检测请求 header ，浏览器环境之类的，不是 server 端的检测。 回到刚刚的问题，不带 client_id 也没什么问题，但是现在访问的需要带 turnstile token 的 API 都是 oauth 验证之后才能访问吧？那我觉得把 "请求解 turnstile" 和 "需要注册 oauth app" 这两件事情绑定也没什么副作用。

少查一次库（

2024-10-14 06:09 UTC, everpcpc commented
> 我的意思是 turnstile 自身的各种检测，他可能会检测请求 header ，浏览器环境之类的，不是 server 端的检测。 回到刚刚的问题，不带 client_id 也没什么问题，但是现在访问的需要带 turnstile token 的 API 都是 oauth 验证之后才能访问吧？那我觉得把 "请求解 turnstile" 和 "需要注册 oauth app" 这两件事情绑定也没什么副作用。

哦懂了。
不过 turnstile 跟 oauth 流程不同，只有用 client_id 请求 code 的阶段，没有 client_id+client_secret+code 做 token exchange 的阶段，server 端没有办法对 client 进行足够的验证。

2024-10-14 06:12 UTC, MisakaTAT commented
那看看新 commit 行吗（

2024-10-14 06:14 UTC, everpcpc commented on routes/demo/index.ts
> +        throw BadRequestError('Invalid redirect_uri. It must start with http:// or https://');
redirect_uri 可能是 `bangumi://callback` 这样的东西，不能做 http 的假设

2024-10-14 06:16 UTC, MisakaTAT commented on routes/demo/index.ts
> +        throw BadRequestError('Invalid redirect_uri. It must start with http:// or https://');
那就不设限，支持自定义scheme

2024-10-14 06:17 UTC, MisakaTAT commented on routes/demo/index.ts
> +        throw BadRequestError('Invalid redirect_uri. It must start with http:// or https://');
忘记了有本地唤起app之类的需求了（

2024-10-14 06:17 UTC, everpcpc approved these changes

2024-10-14 06:17 UTC, MisakaTAT commented
window.location.href 不知道会不会有啥问题，不确定（

2024-10-14 06:18 UTC, MisakaTAT commented
> window.location.href 不知道会不会有啥问题，不确定（

应该不会吧，模板里好像也只能这么跳转

2024-10-14 06:19 UTC, everpcpc commented on bin/main.ts
> +  logger.info(`turnstile   http://127.0.0.1:${port}/demo/turnstile`);
（话说这个 `/demo` 能不能改改 QAQ

2024-10-14 06:19 UTC, MisakaTAT commented on bin/main.ts
> +  logger.info(`turnstile   http://127.0.0.1:${port}/demo/turnstile`);
我看都是demo，就这么写了（

2024-10-14 06:28 UTC, everpcpc commented on templates/turnstile.liquid
> +{% assign title = 'turnstile' %}
这个 template 好像没有继承 layout？

2024-10-14 06:32 UTC, StageGuard commented on templates/turnstile.liquid
> +{% assign title = 'turnstile' %}
如果可以不继承的话最好，这样可以让 app 以 UI 视图/组件的形式嵌入

2024-10-14 06:38 UTC, MisakaTAT commented on templates/turnstile.liquid
> +{% assign title = 'turnstile' %}
> 这个 template 好像没有继承 layout？

考虑到可能需要直接嵌入app，我就没有继承layout。

2024-10-14 06:40 UTC, everpcpc commented on templates/turnstile.liquid
> +{% assign title = 'turnstile' %}
如果要直接嵌入 app 的话 template 就不是这样的写法了，assign title 和 block/endblock 都不需要了

2024-10-14 06:43 UTC, MisakaTAT commented on templates/turnstile.liquid
> +{% assign title = 'turnstile' %}
> 如果要直接嵌入 app 的话 template 就不是这样的写法了，assign title 和 block/endblock 都不需要了

没用过 liquidjs，照葫芦画瓢。

直接这样吗？不过好像不改的话效果好像也一样？

```js
<script
  src='https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback'
  async
  defer
></script>

<div id='turnstile-container'></div>

<script>
  window.onload = function () {
    if (typeof turnstile !== 'undefined') {
      turnstile.render('#turnstile-container', {
        sitekey: '{{ TURNSTILE_SITE_KEY }}',
        theme: '{{ turnstile_theme }}',
        callback: turnstileCallback,
      });
    } else {
      console.error('Turnstile API not loaded.');
    }
  };

  function turnstileCallback(token) {
    const redirectUri = `{{ redirect_uri }}?token=${token}`;
    window.location.href = redirectUri;
  }
</script>

```

2024-10-14 06:46 UTC, everpcpc commented on templates/turnstile.liquid
> +{% assign title = 'turnstile' %}
不太清楚内嵌是怎么做的，不过是不是还是需要一个完整的 `html` block 的（

2024-10-14 06:49 UTC, MisakaTAT commented on templates/turnstile.liquid
> +{% assign title = 'turnstile' %}
最终渲染出来是完整的
![QQ_1728888584664](https://github.com/user-attachments/assets/f4e03403-9d77-4ace-917f-e7056ea9ce45)

2024-10-14 06:50 UTC, MisakaTAT commented on templates/turnstile.liquid
> +{% assign title = 'turnstile' %}
我觉得这个应该没问题

2024-10-14 06:52 UTC, StageGuard commented on templates/turnstile.liquid
> +{% assign title = 'turnstile' %}
草，我想表达的内嵌意思是 app 里开个 webview 渲染，不是内嵌到网页里

2024-10-14 11:51 UTC, StageGuard commented
merge when

2024-10-14 12:31 UTC, trim21 commented on bin/main.ts
> +  logger.info(`turnstile   http://127.0.0.1:${port}/demo/turnstile`);
别加console了

2024-10-14 12:31 UTC, trim21 commented on bin/main.ts
> +  logger.info(`turnstile   http://127.0.0.1:${port}/demo/turnstile`);
要不考虑一下放在别的path？

2024-10-14 12:42 UTC, trim21 commented on templates/turnstile.liquid
> +    const redirectUri = `{{ redirect_uri }}?token=${token}`;
这里是不是有点问题，uri如火query的话就不对了

2024-10-14 12:46 UTC, trim21 commented
> > 感觉不需要再验证一次 client_id，带 redirect_uri 就好。 因为即使非认证客户端拿到一个 cf token 也没什么影响，毕竟自己随便本地写个页面加载下 cf 的 js 也能拿到这个 token 的
> 
> 之前评论接口 merge 的时候我测试过在本地页面填 bgm 的 sitekey 加载验证，发现 turnstile 会报错，cf 提供的 dummy key 就可以，所以我觉得 turnstile 应该是没办法随便就能过的，有很多检测手段

因为sitekey跟域名是绑定的，一个域名的site key不能用在别的域名

2024-10-15 01:20 UTC, MisakaTAT commented
function turnstileCallback(token) {
    const redirectUri = '{{ redirect_uri }}';
    const separator = redirectUri.includes('?') ? '&' : '?';
    window.location.href = `${redirectUri}${separator}token=${encodeURIComponent(token)}`;
  }优化代码，可能有多个? 如何校验是否为合法url

2024-10-15 01:27 UTC, everpcpc commented on templates/turnstile.liquid
> +    const redirectUri = '{{ redirect_uri }}';
```suggestion
    const u = new URL('{{ redirect_uri }}');
    u.searchParams.set('token', token);
```

直接这样就好了？

2024-10-15 01:31 UTC, MisakaTAT commented on templates/turnstile.liquid
> +    const redirectUri = '{{ redirect_uri }}';
原生 js 用不了 URL 吧？

2024-10-15 01:34 UTC, everpcpc commented on templates/turnstile.liquid
> +    const redirectUri = '{{ redirect_uri }}';
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

2024-10-15 01:35 UTC, MisakaTAT commented on templates/turnstile.liquid
> +    const redirectUri = '{{ redirect_uri }}';
草（，可以，我之前是这么写，当时好像是URL undefined 才改掉的

2024-10-15 01:47 UTC, trim21 commented on templates/turnstile.liquid
> +    const redirectUri = '{{ redirect_uri }}';
全局作用域的 `URL` 是先加在浏览器才加在nodejs的。。。

2024-10-15 01:48 UTC, trim21 commented on templates/turnstile.liquid
> +    const redirectUri = '{{ redirect_uri }}';
盲猜这里会出现escape问题，应该 tojson 一下再转回来

2024-10-15 02:05 UTC, trim21 commented on templates/turnstile.liquid
> +    const redirectUri = '{{ redirect_uri }}';
`http://127.0.0.1:4000/p1/turnstile?redirect_uri=https%3A%2F%2Fexample.com%2Fa%3Fa%3D1%26b%3D2` (

2024-10-15 02:49 UTC, trim21 requested changes
这个redirect_uri会递归…

2024-10-15 03:31 UTC, trim21 commented on routes/private/routes/user.ts
> +      const redirectUri = decodeURIComponent(req.query.redirect_uri);
不是，这里是已经解码过的内容了

2024-10-15 03:45 UTC, MisakaTAT commented on routes/private/routes/user.ts
> +      const redirectUri = decodeURIComponent(req.query.redirect_uri);
原来说的是模板转义（

2024-10-15 03:47 UTC, trim21 commented on routes/private/routes/user.ts
> +      if (!allowedRedirectUris.some((allowedUri) => redirectUri.startsWith(allowedUri))) {
用Set

2024-10-15 03:50 UTC, trim21 commented
我错了（），刚才没仔细看，一开始以为是单纯的相等检查，才注意到是startswith，还是用array吧。

2024-10-15 03:50 UTC, MisakaTAT commented
> 我错了（），刚才没仔细看，一开始以为是单纯的相等检查，才注意到是startswith，还是用array吧。

草（

2024-10-15 03:51 UTC, everpcpc commented on routes/private/routes/user.ts
> +  const allowedRedirectUris: string[] = ['https://example.com'];
先加一个 `bangumi://`

2024-10-15 03:52 UTC, trim21 commented
ani 的呢？

2024-10-15 03:56 UTC, trim21 commented on routes/private/routes/user.ts
> +      const { protocol, hostname } = parsedUrl;
不是，我的意思是把 `http://example.com` 改成 `http://example.com/` 就有域名检查了。。。

2024-10-15 03:56 UTC, MisakaTAT commented on routes/private/routes/user.ts
> +  const allowedRedirectUris: string[] = ['https://example.com'];
直接bangumi://吗

2024-10-15 03:57 UTC, MisakaTAT commented on routes/private/routes/user.ts
> +      const { protocol, hostname } = parsedUrl;
草

2024-10-15 04:01 UTC, merged